user: 3
group: 3
permission:
  read: 3
  write: 1
  exec: 2
  exec-sticky: 5
  no-access: 245
  octal: 6
  acl: dark_cyan
  context: 4
date:
  hour-old: 250
  day-old: 245
  older: 240
size:
  none: 245
  small: 119
  medium: 3
  large: 1
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
git-status:
  default: 245
  unmodified: 245
  ignored: 245
  new-in-index: 2
  new-in-workdir: 2
  typechange: 3
  deleted: 1
  renamed: 2
  modified: 3
  conflicted: 1
