#       
name:
  .trash: 
  .cargo: 
  .emacs.d: 
  .gnome: 
  music: 
  library:  # 
  games: 
  go:  # 
  uminho:  # 
  ctf: 
  mk7: 
  exploits: 
  books: 
  packages: 
  snap: 
  .snap: 
  steam:  # 
  .steam:  # 
  java: 
  .java: 
  arduino: 
  .arduino15: 
  fonts: 
  .fonts: 
  mozilla: 
  .mozilla: 
  git: 
  .git: 
  .gitignore: 
  .gitconfig: 
  .gitattributes: 
  .gitmodules: 
  .gitkeep: 
  .github: 
  .copilot-cli-access-token: 
  .copilot-cli-copilot-token: 
  .fzf: 󱆃
  .autojump: 󱆃
  .bash: 󱆃
  .bashrc: 󱆃
  .bash_history: 󱆃
  .bash_logout: 󱆃
  .bash_profile: 󱆃
  .profile: 󱆃
  .bash_aliases: 󱆃
  .selected_editor: 
  .nanorc: 
  .sudo_as_admin_successful: 
  .wakatime.cfg: 
  .wakatime.bdb: 
  a.out: 
extension:
  go:  # 
  py: 
  js: 
  json: 
  md: 
  m: 
  c: 
  h: 
  # cpp: 
  # hpp: 
  hs: 
  rs: 
  asc: 
  gpg: 
filetype:
  dir: 
  file: 
  pipe: 󰈲
  socket: 󰆨
  executable: 
  symlink-dir: 
  symlink-file: 
  device-char: 
  device-block: 󰜫
  special: 
